language: cpp
env:
      - CPP11=1
compiler:
      - gcc
      - clang
before_install:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -qq
addons:
      apt:
            packages:
                  - libstdc++-4.8-dev
                  - g++-4.8
                  - gcc-4.8
script: make autoschedule
